spring:
  application:
    name: hateoas-demo
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:./data/testdb
    username: sa
    password:
    schema: classpath:sql/schema.sql
    initialization-mode: always
  h2:
    console:
      enabled: true
